"""empty message

Revision ID: e1a5e5349afa
Revises: 92c8f471d2dc
Create Date: 2020-01-10 11:51:53.279859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a5e5349afa'
down_revision = '92c8f471d2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_and_authors',
    sa.Column('authors.id', sa.Integer(), nullable=False),
    sa.Column('books.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authors.id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['books.id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('authors.id', 'books.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_and_authors')
    # ### end Alembic commands ###
